### PR TITLE
Add file descriptor features (open, read, next, write, append, flush, close)

### PR DESCRIPTION
**Pull request by dysinger**
Please review. Let me know if you like anything different. :)

### CODE REVIEW

**Comment by dysinger** [comment]
@garyb @jdegoes ^ plz review & let me know what you want different

**Comment by jdegoes** [comment]
I haven't used or worked on this library, but looks good to me. I think the wrapper libs need to be very low-level so lots of authors can build on top of them. If they get too opinionated, that encourages fragmentation.

@joneshf  may be a good one to check here.

**Comment by dysinger** [comment]
Well low-level is what I've tried to do here. If it's not low-level enough then let's talk about it.  I'm simply translating, with as little code as possible, the synchronous file handling bits from Node.js "fs".

**Comment by jdegoes** [comment]
Yes, I agree, looked at the perfect level to me. :+1:

**Comment by garyb** [comment]
Looks good to me too at a glance, but sorry, I'm a bit busy tonight - will try to get some time to review/merge tomorrow!

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
